export const LOADING_PHOTOS_REQUEST = 'LOADING_PHOTOS_REQUEST';
export const LOADING_PHOTOS_SUCCESS = 'LOADING_PHOTOS_SUCCESS';
export const LOADING_PHOTOS_FAILURE = 'LOADING_PHOTOS_FAILURE';
export const UPDATE_GALLERY = 'UPDATE_GALLERY';
export const CHANGE_VIEW_TYPE = 'CHANGE_VIEW_TYPE';
